  - id: homekit_start
    alias: 'Start HomeKit'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:02  # Waits 5 minutes
      - service: homekit.start

  - id: rpi_power_issue
    alias: Power Problem Notification
    trigger:
    - platform: numeric_state
      entity_id: sensor.rpi_power_status
      above: 0
      for:
        minutes: 1
    condition:
    action:
      service: persistent_notification.create
      data:
        message: "Charger reported {{ states.sensor.rpi_power_status.state }}"
        title: "RPI Power Issue"
  
  - id: north_balcony_pump_auto_off
    alias: 'Pump for Boiler: turn off (auto)'
    trigger:
      - platform: state
        entity_id: switch.plug_158d00019d0d0c
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.boiler_pump_timer
  
  - id: north_balcony_pump_reset_timer
    alias: 'Pump for Boiler: reset timer'
    trigger: 
      - platform: state
        entity_id: switch.plug_158d00019d0d0c
        to: 'off'
    action:
      - service: script.turn_off
        entity_id: script.boiler_pump_timer
        