homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 31.2304
  longitude: 121.4737
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 4
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai
  # Load pakcages from folder packages
  packages: !include_dir_named packages/
  # Customization file
  customize: !include_dir_merge_named customize/
  #customize_domain:
  #  device_tracker:
  #    hidden: true

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   ssl_certificate: !secret my_ssl_crt
#   ssl_key: !secret my_ssl_key
#   base_url: !secret secret_base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - netgear_router

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# KNX devices
knx:
  config_file: 'domains/xknx.yaml'
  tunneling:
    host: !secret knx_router_ip
    port: 3671
    local_ip: !secret local_ip
    #fire_event: True

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_gateway_mac
      key: !secret xiaomi_gateway_key

recorder: !include domains/recorder.yaml

homekit: !include domains/homekit.yaml

cover: !include domains/cover.yaml
climate: !include domains/climate.yaml
light: !include domains/light.yaml
device_tracker: !include domains/device_tracker.yaml
sensor: !include_dir_merge_list domains/sensor/
automation: !include automations.yaml
script: !include scripts.yaml
group: !include_dir_merge_named groups/
# new in hass 0.87
system_health:
# This component allows you to write Python scripts that are exposed as 
# services in Home Assistant. Each Python file created in the
# <config>/python_scripts/ folder will be exposed as a service. The content 
# is not cached so you can easily develop: edit file, save changes, call 
# service. The scripts are run in a sandboxed environment. 
python_script:

speedtestdotnet:
  scan_interval:
    minutes: 60
  monitored_conditions:
    - ping
    - download
    - upload