
- platform: template
  sensors: 
    knx_router: 
      friendly_name: KNX Router
      value_template: "{% if is_state('device_tracker.d09b05075597', 'home') %}online{% else %}offline{% endif %}"
      icon_template: mdi:home-variant  
    raspberrypi: 
      friendly_name: Raspberrypi 3B+
      value_template: "{% if is_state('device_tracker.raspberrypi', 'home') %}online{% else %}offline{% endif %}"
      icon_template: mdi:raspberrypi
    wndrmacv2: 
      friendly_name: OpenWrt on WndrMacV2
      value_template: "{% if is_state('device_tracker.openwrt', 'home') %}online{% else %}offline{% endif %}"
      icon_template: mdi:router-wireless
    lumigatewayv3:
      friendly_name: 小米网关
      value_template: "{% if is_state('device_tracker.lumigatewayv3_miio57655989', 'home') %}online{% else %}offline{% endif %}"
      icon_template: mdi:radio-tower
    chuangmi_camera:
      friendly_name: 小米智能相机
      value_template: "{% if is_state('device_tracker.chuangmi_camera_ipc009', 'home') %}online{% else %}offline{% endif %}"
      icon_template: mdi:webcam
    mitv4a: 
      friendly_name: 小米4A电视
      value_template: "{% if is_state('device_tracker.mitv4a544d24be36820c49', 'home') %}online{% else %}offline{% endif %}"
      icon_template: mdi:television
    oneplusone: 
      friendly_name: Oneplus One (IP Camera)
      value_template: "{% if is_state('device_tracker.c0eefb03948f', 'home') %}online{% else %}offline{% endif %}"
      icon_template: mdi:cellphone-android
    nexus5: 
      friendly_name: Nexus 5 (IP Camera)
      value_template: "{% if is_state('device_tracker.android8f98d6795a53dd81', 'home') %}online{% else %}offline{% endif %}"
      icon_template: mdi:cellphone-android      
    nexus7_2013: 
      friendly_name: Nexus7 2013 (Screen)
      value_template: "{% if is_state('device_tracker.android65fb25084c7cc7d3', 'home') %}online{% else %}offline{% endif %}"
      icon_template: mdi:tablet-android


