homeassistant:
  # Customization file
  customize:
    automation.entrance_motion_lights_on:
      hidden: true 
    automation.entrance_motion_lights_off:
      hidden: true 
    script.entrance_spotlight_timer:
      hidden: true
    binary_sensor.entrance_too_dark:
      hidden: true

input_boolean:
  entrance_spotlight_automode:
    name: 玄关灯自动模式
    initial: on
    icon: mdi:autorenew

input_number:
  entrance_spotlight_brightness:
    name: 玄关灯亮度（自动模式）
    initial: 153
    min: 40
    max: 255
    step: 1
    icon: mdi:brightness-7
  entrance_spotlight_delay:
    name: 关灯延时（自动模式）
    initial: 1
    min: 1
    max: 10
    step: 1
    unit_of_measurement: 'min'
    icon: mdi:clock-end
  entrance_spotlight_lm_threshold:
    name: 开灯亮度阈值（自动模式）
    initial: 150
    min: 50
    max: 350
    step: 10
    unit_of_measurement: 'lm'
    icon: mdi:brightness-5

binary_sensor:
  - platform: template
    sensors:
      entrance_too_dark:
        friendly_name: 'Dark Entrance'
        value_template: '{{ states.sensor.illumination_34ce008dcf02.state | int < states.input_number.entrance_spotlight_lm_threshold.state | int}}'

automation:
  - id: entrance_on_motion_detected
    alias: 'Entrance Motion Lights On'
    trigger:
      - platform: state
        entity_id: binary_sensor.entrance_sensor
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.entrance_spotlight_automode
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: below_horizon
        #state: above_horizon
      - condition: state
        entity_id: binary_sensor.entrance_too_dark
        state: 'on'
      - condition: or
        conditions:
        - condition: state
          entity_id: group.living_room_lights
          state: 'off'
        - condition: state
          entity_id: group.dining_room_lights
          state: 'off'
    action:
      - service: script.turn_off
        entity_id: script.entrance_spotlight_timer
      - service: light.turn_on
        entity_id: light.entrance_spotlight
        data_template: 
          brightness: '{{states.input_number.entrance_spotlight_brightness.state | int}}'
  
  - id: entrance_on_poeple_left
    alias: 'Entrance Motion Lights Off'
    trigger: 
      - platform: state
        entity_id: binary_sensor.entrance_sensor
        to: 'off'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.entrance_spotlight_automode
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: below_horizon
        #state: above_horizon
      #- condition: state
      #  entity_id: light.entrance_spotlight
      #  state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.entrance_spotlight_timer

script:
  entrance_spotlight_timer:
    alias: 'Entrance Spotlight Timer (auto turn off)'
    sequence:
      - delay: '00:{{ states.input_number.entrance_spotlight_delay.state | int }}:00'
      - service: homeassistant.turn_off
        data:
          entity_id: light.entrance_spotlight

group:
  entrance_light_ctrl:
    name: 玄关顶灯控制(自动)
    view: false
    icon: mdi:home-automation
    entities:
    - input_boolean.entrance_spotlight_automode
    - input_number.entrance_spotlight_brightness
    - input_number.entrance_spotlight_delay
    - input_number.entrance_spotlight_lm_threshold
    - automation.entrance_motion_lights_on
    - automation.entrance_motion_lights_off
    - script.entrance_spotlight_timer
