homeassistant:
  # Customization file
  customize:
    automation.entrance_motion_lights_on:
      hidden: true 
    automation.entrance_motion_lights_off:
      hidden: true 
    script.entrance_spotlight_timer:
      hidden: true
    binary_sensor.entrance_too_dark:
      hidden: true

input_boolean:
  entrance_spotlight_automode:
    name: 玄关灯自动模式
    # Disable initial setting otherwise state of the input_boolean won't be restored
    # initial: on
    icon: mdi:brightness-auto

input_number:
  entrance_spotlight_brightness:
    name: 玄关灯亮度（自动模式）
    # Disable initial setting otherwise state of the input_number won't be restored
    #initial: 153
    min: 40
    max: 255
    step: 1
    icon: mdi:brightness-7

  entrance_spotlight_delay:
    name: 关灯延时（自动模式）
    # Disable initial setting otherwise state of the input_number won't be restored
    #initial: 30
    min: 0
    max: 300
    step: 5
    unit_of_measurement: 'sec'
    icon: mdi:timer

  entrance_spotlight_lm_threshold:
    name: 开灯亮度阈值（自动模式）
    # Disable initial setting otherwise state of the input_number won't be restored    
    #initial: 150
    min: 50
    max: 350
    step: 10
    unit_of_measurement: 'lm'
    icon: mdi:brightness-5

binary_sensor:
  - platform: template
    sensors:
      entrance_too_dark:
        friendly_name: 'Dark Entrance'
        value_template: '{{ states.sensor.illumination_34ce008dcf02.state | int < states.input_number.entrance_spotlight_lm_threshold.state | int}}'

automation:
  - id: entrance_on_motion_detected
    alias: 'Entrance Motion Lights On'
    trigger:
      - platform: state
        entity_id: binary_sensor.entrance_sensor
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.entrance_spotlight_automode
        state: 'on'
      - condition: state
        entity_id: binary_sensor.entrance_too_dark
        state: 'on'
      - condition: or
        conditions:
        - condition: sun
          after: sunset
          after_offset: "-01:00:00"
        - condition: sun
          before: sunrise
          before_offset: "+01:00:00"
      - condition: or
        conditions:
        - condition: state
          entity_id: group.living_room_lights
          state: 'off'
        - condition: state
          entity_id: group.dining_room_lights
          state: 'off'
    action:
      - service: script.turn_off
        entity_id: script.entrance_spotlight_timer
      # light.turn_on with birightness will only set brightness of the KNX light
      # the internal switch state won't be updated as there is no switch_state_address in my case
      # So my workaround is turn on the light (switch) and then adjust the light (brightness)
      - service: light.turn_on
        entity_id: light.entrance_spotlight        
      - service: light.turn_on
        entity_id: light.entrance_spotlight
        data_template: 
          brightness: '{{states.input_number.entrance_spotlight_brightness.state | int}}'
  
  - id: entrance_on_poeple_left
    alias: 'Entrance Motion Lights Off'
    trigger: 
      - platform: state
        entity_id: binary_sensor.entrance_sensor
        to: 'off'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.entrance_spotlight_automode
        state: 'on'
      - condition: or
        conditions:
        # on/off state of this light is not always consistent with real condition
        # try to use both on/off state of the switch and brightness value as conditions
        - condition: state
          entity_id: light.entrance_spotlight
          state: 'on'          
        - condition: numeric_state
          entity_id: light.entrace_spotlight
          value_template: '{{ state.attributes.brightness }}'
          above: 0
    action:
      - service: script.turn_on
        entity_id: script.entrance_spotlight_timer

script:
  entrance_spotlight_timer:
    alias: 'Entrance Spotlight Timer (auto turn off)'
    sequence:
      - delay: 
          seconds: '{{ states.input_number.entrance_spotlight_delay.state | int }}'
      - service: homeassistant.turn_off
        data:
          entity_id: light.entrance_spotlight

group:
  entrance_light_ctrl:
    name: 玄关灯控制(自动)
    # view: false
    icon: mdi:home-automation
    entities:
    - input_boolean.entrance_spotlight_automode
    - input_number.entrance_spotlight_brightness
    - input_number.entrance_spotlight_delay
    - input_number.entrance_spotlight_lm_threshold
    - automation.entrance_motion_lights_on
    - automation.entrance_motion_lights_off
    - script.entrance_spotlight_timer
