homeassistant:
  # Customization file
  customize:
    fan.xiaomi_air_purifier_v2_1:
      friendly_name: Air Purfier (控件)

fan:
  - platform: xiaomi_miio
    name: xiaomi_air_purifier_v2_1
    host: !secret miio_air_purifier_ip
    token: !secret miio_air_purifier_token
    model: zhimi.airpurifier.m1

sensor:
  - platform: template
    sensors:
      xiaomi_apv2_1_aqi:
        friendly_name: 空气质量
        value_template: '{{ states.fan.xiaomi_air_purifier_v2_1.attributes.aqi }}'
        icon_template: mdi:poll
        unit_of_measurement: AQI
      xiaomi_apv2_1_temp:
        friendly_name: 温度
        value_template: '{{ states.fan.xiaomi_air_purifier_v2_1.attributes.temperature }}'
        icon_template: mdi:thermometer
        unit_of_measurement: '°C'
      xiaomi_apv2_1_rh:
        friendly_name: 湿度
        value_template: '{{ states.fan.xiaomi_air_purifier_v2_1.attributes.humidity }}'
        icon_template: mdi:water-percent
        unit_of_measurement: '%'

group:
  xiaomi_air_purifier_v2_1:
    name: 小米空气净化器
    view: false
    icon: mdi:fan
    entities:
      - fan.xiaomi_air_purifier_v2_1
      - sensor.xiaomi_apv2_1_aqi
      - sensor.xiaomi_apv2_1_temp
      - sensor.xiaomi_apv2_1_rh